### ISSUE TITLE
fourCcList description should explicitly state support for receiving those codecs

### ISSUE THREAD

**Issue by zenomt** [veovera/enhanced-rtmp#14]
the `fourCcList` currently says it contains strings each "representing a supported video codec". as discussed at https://github.com/veovera/enhanced-rtmp/issues/11#issuecomment-1563194176 , the description should be clarified to say that this lists codecs that the client is able to receive and process.

the practical historical usage of the `videoCodecs` and `audioCodecs` bitmaps sent by the client in the `connect` command has been to indicate which codecs the client is able to receive. historically it's been irrelevant to the server what codecs a client can send, since the server could handle all traditional RTMP codecs.

**Comment by veovera** [comment]
Fixed please see <[link](https://veovera.org/docs/enhanced/enhanced-rtmp-v2#enhancing-netconnection-connect-command)>
