### ISSUE TITLE
consider enabling Discussions on this repo

### ISSUE THREAD

**Issue by zenomt** [veovera/enhanced-rtmp#16]
i wanted to ask if folks have test/sample media (FLVs) with Enhanced content, and clients & servers to test/interop with. i think that sort of thing belongs in a Discussion rather than an Issue. please consider enabling Discussions on this repo to discuss that and other topics that don't belong in Issues. :)

perhaps eventually links to test media and compatible clients & servers could be on a wiki page or in the README.

**Comment by veovera** [comment]
discussions are enabled!
