### ISSUE TITLE
latest enhanced-rtmp-v2.pdf has an improperly framed page

### ISSUE THREAD

**Issue by zenomt** [veovera/enhanced-rtmp#33]
page 20 of the PDF as of https://github.com/veovera/enhanced-rtmp/commit/e5e04a65a6c71b0f2f32673ba163e1ecdb3b9556 seems to be zoomed in, so you can't read all of the text. this looks like a PDF conversion problem.

**Comment by veovera** [comment]
Fixed, turned out to be somewhat tricky to fix.
