### ISSUE TITLE
No way of retrieving the metadata for multitrack streaming

### ISSUE THREAD

**Issue by murillo128** [veovera/enhanced-rtmp#37]
Currently we retrieve certain audio/video properties on the `onMetaData` command, like `width`, `heigth`,`framerate` and `videodatarate`.

When multitrack streaming is used, each track could have different values and there is no way to specify them, could we add them to the `VideoPacketType.Metadata`?

**Comment by Thulinma** [comment]
Perhaps even more prudent: it's unclear to me how sequencestart would be conveyed in a multitrack stream, since those two types seem to be mutually exclusive in the current specification.
Normally, you could extract the properties @murillo128 refers to from the sequencestart data (not possible for all codecs, but it is if you combine that data with a keyframe).

**Comment by veovera** [comment]
> unclear to me how sequencestart would be conveyed in a multitrack stream

@Thulinma Regarding how `SequenceStart` is conveyed in a multitrack stream, it would be helpful to review the 

[`if (videoPacketType == VideoPacketType.SequenceStart)`](https://github.com/veovera/enhanced-rtmp/blob/6445c80106c418ebe6bb18602e1c86645b2c1778/docs/enhanced/enhanced-rtmp-v2.md?plain=1#L1077)

signal. This signal is applied on a per-track basis. If there are concerns about how it fits into multitrack streams, it may be useful to create a separate issue to address this specifically, apart from metadata discussions.

**Comment by murillo128** [comment]
I am specifically interested in the video framerate and bitrate as that info can't be extracted from the codec media data.

**Comment by Thulinma** [comment]
> > unclear to me how sequencestart would be conveyed in a multitrack stream
> 
> @Thulinma Regarding how `SequenceStart` is conveyed in a multitrack stream, it would be helpful to review the
> 
> [`if (videoPacketType == VideoPacketType.SequenceStart)`](https://github.com/veovera/enhanced-rtmp/blob/6445c80106c418ebe6bb18602e1c86645b2c1778/docs/enhanced/enhanced-rtmp-v2.md?plain=1#L1077)
> 
> signal. This signal is applied on a per-track basis. If there are concerns about how it fits into multitrack streams, it may be useful to create a separate issue to address this specifically, apart from metadata discussions.

Ah yes, I did not notice that in the spec the variable `videoPacketType` is actually read twice in case of multitrack. It might be helpful to put a note about that in the text, as it is very easy to accidentally miss that detail 😅. Never mind - my concern does not apply at all. Sorry for the confusion!

**Comment by murillo128** [comment]
@veovera any feedback on the metadata issue?  are you ok if I submit a PR to the spec for adding the missing metadata to the videoPackey type? 

I plan to submit a PR to OBS for implementing it,  but need a spec (even a draft) to refer to.

**Comment by veovera** [comment]
@murillo128, I understand the issue but haven’t had a chance to take a close look yet. It’s next up once I wrap up my current work. While we're on the topic:

- Are you sending multiple tracks in one message, or is it one track per message?

- I'm curious—how are you utilizing the multitrack feature?

- It sounds like you might have a proposal for the missing data. Would you mind describing it here before submitting a PR?

Thanks in advance!

**Comment by murillo128** [comment]
OBS implemented [Multitrack Streaming via Enhanced RTMP](https://github.com/veovera/enhanced-rtmp/blob/main/docs/enhanced/enhanced-rtmp-v2.md#multitrack-streaming-via-enhanced-rtmp) for [twitch and IVS](https://help.twitch.tv/s/article/multiple-encodes?language=en_US). I am implementing support for the same feature on my server to be able to receive the multitrack encodings from OBS as Twitch/IVS already does.

OBS already supports sending the metadata with the `colorInfo` object per track  https://github.com/obsproject/obs-studio/blob/df742ed0323feffa903381c16d81477db332b9b3/plugins/obs-outputs/flv-mux.c#L584.

The idea would be to extend the `VideoPacketType.Metadata` in:

> To support various types of video metadata, the legacy [[FLV](https://github.com/veovera/enhanced-rtmp/blob/main/docs/enhanced/enhanced-rtmp-v2.md#flv)] specification has been enhanced. The VideoTagHeader has been extended to define a new VideoPacketType.Metadata (see ExVideoTagHeader table in [Enhanced Video](https://github.com/veovera/enhanced-rtmp/blob/main/docs/enhanced/enhanced-rtmp-v2.md#enhanced-video) section) whose payload will contain an AMF-encoded metadata. The metadata will be represented by a series of [name, value] pairs. For now the only defined [name, value] pair is ["colorInfo", Object].

with the properties already defined in the `onMetaData` object. So the metadata will be

| Property    | Type|
| -------- | ------- |
| colorInfo  | colorInfo Object    |
|framerate          |number  |
|height              |number |
|videodatarate      |number   |
|width              |number   |

**Comment by veovera** [comment]
> The idea would be to extend the `VideoPacketType.Metadata` in:

Hi @murillo128 

That is one way to accomplish this, but it limits to video info only. We are leaning towards adding a couple of properties (one for video and one for audio) to the argument object in the onMetaData callback. These properties would be maps containing trackIDs and additional data for each track. This approach would maintain the current delivery method through the onMetaData callback. We aim to finalize the specifications by the end of the day September 9 or 10. Please let us know if you foresee any issues with this plan.

**Comment by murillo128** [comment]
having an array of properties in the onMetadata callback would work also. Let me know if you could help you in any way.

**Comment by veovera** [comment]
@murillo128 I am thinking to add something like this to the spec. LMK if perhaps something is missing or could be restated.

## Enhancing onMetaData

FLV metadata SHALL be encapsulated within a [**SCRIPTDATA**](https://veovera.github.io/enhanced-rtmp/docs/legacy/video-file-format-v10-1-spec.pdf#page=80) segment, which includes a [**ScriptTagBody**](https://veovera.github.io/enhanced-rtmp/docs/legacy/video-file-format-v10-1-spec.pdf#page=80) encoded in the Action Message Format (AMF). Importantly, this metadata SHALL always remain unencrypted, even when the FLV content itself is encrypted. This design choice is essential for allowing various FLV parsers to successfully stream the FLV content and for enabling media players to provide contextual information to the user. \
&nbsp; \
The **ScriptTagBody** is structured to encapsulate method invocations. It consists of an item containing a method name (e.g., **onMetaData**) along with a corresponding set of arguments. \
&nbsp; \
To signal FLV metadata, the item within the **ScriptTagBody** MUST encapsulate the method name **onMetaData**, along with a single argument of type ECMA array. This array holds metadata properties, the availability of which may vary depending on the software used to create the FLV. Typical **onMetaData** argument properties include, but are not limited to: \
&nbsp; \
**Table**: Typical properties found in the **onMetaData** argument object

```txt
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦Property              ¦Type                        ¦Comment                                                                        ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦audiocodecid          ¦number                      ¦Audio codec ID used in the file: See AudioTagHeader of the legacy [FLV]        ¦
¦                      ¦                            ¦specification for available CodecID values.                                    ¦
¦                      ¦                            ¦                                                                               ¦
¦                      ¦                            ¦                                                                               ¦
¦                      ¦                            ¦When [FourCC] is used to signal the codec, this property is set to a FOURCC    ¦
¦                      ¦                            ¦value. Note: A FOURCC value is big-endian relative to the underlying ASCII     ¦
¦                      ¦                            ¦character sequence (e.g., "Opus" == 0x4F707573 == 1332770163.0).               ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦audiodatarate         ¦number                      ¦Audio bitrate, in kilobits per second                                          ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦audiodelay            ¦number                      ¦Delay introduced by the audio codec, in seconds                                ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦audiosamplerate       ¦number                      ¦Frequency at which the audio stream is replayed                                ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦audiosamplesize       ¦number                      ¦Resolution of a single audio sample                                            ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦canSeekToEnd          ¦boolean                     ¦Indicating the last video frame is a key frame                                 ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦creationdate          ¦string                      ¦Creation date and time                                                         ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦duration              ¦number                      ¦Total duration of the file, in seconds                                         ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦filesize              ¦number                      ¦Total size of the file, in bytes                                               ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦framerate             ¦number                      ¦Number of frames per second                                                    ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦height                ¦number                      ¦Height of the video, in pixels                                                 ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦stereo                ¦boolean                     ¦Indicates stereo audio                                                         ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦videocodecid          ¦number                      ¦Video codec ID used in the file: See VideoTagHeader of the legacy [FLV]        ¦
¦                      ¦                            ¦specification for available CodecID values.                                    ¦
¦                      ¦                            ¦                                                                               ¦
¦                      ¦                            ¦When [FourCC] is used to signal the codec, this property is set to a FOURCC    ¦
¦                      ¦                            ¦value. Note: A FOURCC value is big-endian relative to the underlying ASCII     ¦
¦                      ¦                            ¦character sequence (e.g., "av01" == 0x61763031 == 1635135537.0).               ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦videodatarate         ¦number                      ¦Video bitrate, in kilobits per second                                          ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦width                 ¦number                      ¦Width of the video, in pixels                                                  ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
¦audioTrackIdInfoMap   ¦Object                      ¦The audioTrackIdInfoMap and videoTrackIdInfoMap objects are designed to store  ¦
+----------------------+                            ¦metadata for audio and video tracks respectively. Each object uses a TrackId as¦
¦videoTrackIdInfoMap   ¦                            ¦a key to map to properties that detail the unique characteristics of each      ¦
¦                      ¦                            ¦individual track, diverging from the default configurations.                   ¦
¦                      ¦                            ¦                                                                               ¦
¦                      ¦                            ¦- Key-Value Structure:                                                         ¦
¦                      ¦                            ¦  * Keys: Each TrackId acts as a unique identifier for a specific audio or     ¦
¦                      ¦                            ¦    video track.                                                               ¦
¦                      ¦                            ¦  * Values: Track Objects containing metadata that specify characteristics     ¦
¦                      ¦                            ¦    which deviate from the default track settings.                             ¦
¦                      ¦                            ¦- Properties of Each Track Object:                                             ¦
¦                      ¦                            ¦  * These properties detail non-standard configurations needed for custom      ¦
¦                      ¦                            ¦    handling of the track, facilitating specific adjustments to enhance track  ¦
¦                      ¦                            ¦    performance and quality for varied conditions.                             ¦
¦                      ¦                            ¦  * For videoTrackIdInfoMap:                                                   ¦
¦                      ¦                            ¦    + Properties such as width, height, videodatarate, etc. specify video      ¦
¦                      ¦                            ¦      characteristics that differ from standard settings.                      ¦
¦                      ¦                            ¦  * For audioTrackIdInfoMap:                                                   ¦
¦                      ¦                            ¦    + Properties such as audiodatarate, channels, etc., define audio           ¦
¦                      ¦                            ¦      characteristics that differ from standard configurations.                ¦
¦                      ¦                            ¦- Purpose:                                                                     ¦
¦                      ¦                            ¦  * The purpose of these maps is to specify unique properties for each track,  ¦
¦                      ¦                            ¦    ensuring tailored configurations that optimize performance and quality for ¦
¦                      ¦                            ¦    specific media content and delivery scenarios.                             ¦
¦                      ¦                            ¦                                                                               ¦
¦                      ¦                            ¦This structure provides a framework for detailed customization and control over¦
¦                      ¦                            ¦the media tracks, ensuring optimal management and delivery across various types¦
¦                      ¦                            ¦of content and platforms.                                                      ¦
¦                      ¦                            ¦                                                                               ¦
¦                      ¦                            ¦Examples:                                                                      ¦
¦                      ¦                            ¦                                                                               ¦
¦                      ¦                            ¦e.g., 1                                                                        ¦
¦                      ¦                            ¦videoTrackIdInfoMap = {                                                        ¦
¦                      ¦                            ¦  1: {                                                                         ¦
¦                      ¦                            ¦    width: 1024,                                                               ¦
¦                      ¦                            ¦    height: 768,                                                               ¦
¦                      ¦                            ¦    videodatarate: 2000,                                                       ¦
¦                      ¦                            ¦  },                                                                           ¦
¦                      ¦                            ¦                                                                               ¦
¦                      ¦                            ¦  2 : {                                                                        ¦
¦                      ¦                            ¦    width: 3840,                                                               ¦
¦                      ¦                            ¦    height: 2160,                                                              ¦
¦                      ¦                            ¦    videodatarate: 30000,                                                      ¦
¦                      ¦                            ¦  },                                                                           ¦
¦                      ¦                            ¦}                                                                              ¦
¦                      ¦                            ¦                                                                               ¦
¦                      ¦                            ¦e.g., 2                                                                        ¦
¦                      ¦                            ¦audioTrackIdInfoMap = {                                                        ¦
¦                      ¦                            ¦  1: {                                                                         ¦
¦                      ¦                            ¦    audiodatarate: 256,                                                        ¦
¦                      ¦                            ¦    channels: 2,                                                               ¦
¦                      ¦                            ¦    samplerate: 44100,                                                         ¦
¦                      ¦                            ¦  },                                                                           ¦
¦                      ¦                            ¦                                                                               ¦
¦                      ¦                            ¦  2: {                                                                         ¦
¦                      ¦                            ¦    audiodatarate: 320,                                                        ¦
¦                      ¦                            ¦    channels: 1,                                                               ¦
¦                      ¦                            ¦    samplerate: 22050,                                                         ¦
¦                      ¦                            ¦  },                                                                           ¦
¦                      ¦                            ¦}                                                                              ¦
+----------------------+----------------------------+-------------------------------------------------------------------------------+
```

>**Note:**
>
>- The properties **audiocodecid** and **videocodecid** have been enhanced to support FOURCC (Four-byte ASCII code) values. These values are interpreted as UI32 (e.g., "av01").
>- The properties **audioTrackIdInfoMap** and **videoTrackIdInfoMap** are new.

**Comment by murillo128** [comment]
that looks great!

**Comment by veovera** [comment]
@murillo128 

We have incorporated the discussed logic into the [`feature/timestamp-offset`](https://github.com/veovera/enhanced-rtmp/blob/feature/timestamp-offset/docs/enhanced/enhanced-rtmp-v2.md?plain=1#L1425C5-L1425C45) branch. Once this branch stabilizes, we plan to merge it into the `main` branch (which is approaching).

For your reference, here are links to the relevant sections of the specification:

- [Enhancing onMetaData](https://github.com/veovera/enhanced-rtmp/blob/95edc89f699f7e8505a043d210ece24f84d5d6ed/docs/enhanced/enhanced-rtmp-v2.md?plain=1#L383)
- [SCRIPTDATA Multitrack Parameter Handling](https://github.com/veovera/enhanced-rtmp/blob/95edc89f699f7e8505a043d210ece24f84d5d6ed/docs/enhanced/enhanced-rtmp-v2.md?plain=1#L1425C5-L1425C45)

**Comment by murillo128** [comment]
I have implemented the updated spec in obs and in my media server and it is working perfectly. Do you have a timeline on when this could be integrated into the main spec so the PR at OBS can get merged?

**Comment by veovera** [comment]
> I have implemented the updated spec in obs and in my media server and it is working perfectly. Do you have a timeline on when this could be integrated into the main spec so the PR at OBS can get merged?

I'm currently waiting to see if there is any feedback on the PR that would require changes. The main challenge with the PR relates to this issue: [issue link](https://github.com/veovera/enhanced-rtmp/issues/3). I’ll follow up to check if there are any remaining concerns. If not, we will proceed with the merge.

**Comment by veovera** [comment]
This issue has been addressed with the merge of `feature/timestamp-offset` into `main`, which:

- Provided nanosecond precision for timestamps.
- Added support for Multitrack Parameter Handling within SCRIPTDATA.

Closing this issue now. Please reopen if further adjustments are needed.
