### ISSUE TITLE
OBS and SRS supported enhanced RTMP for user to push HEVC via RTMP.

### ISSUE THREAD

**Issue by winlinvip** [veovera/enhanced-rtmp#4]
**This is NOT an issue but a NOTICE**

SRS media server support this extended RTMP specification, so you can push HEVC via RTMP to SRS very easy:

```bash
git clone https://github.com/ossrs/srs.git
cd srs/trunk && ./configure --h265=on && make
./objs/srs -c conf/http.ts.live.conf
```

Then, you can use [OBS 29.1+](https://github.com/obsproject/obs-studio/releases) to push HEVC via RTMP.
Start OBS with the following settings in the `Settings > Stream` tab:

* Server: `rtmp://localhost/live`
* Stream Key: `livestream`
* Encoder: Please select the HEVC hardware encoder.

![image](https://user-images.githubusercontent.com/2777660/230696541-1c63196a-e6a1-4dff-b1ae-8a3693f0ef31.png)

![image](https://user-images.githubusercontent.com/2777660/230696547-82f91459-94a0-4e8e-9ee5-4f6036fedf46.png)

Finally, open the player http://localhost:8080/players/srs_player.html?stream=livestream.ts

Or use VLS or ffplay to play `http://localhost:8080/live/livestream.ts`

**Comment by veovera** [comment]
This is great news and thanks for letting the community know!
