### ISSUE TITLE
What's the plan to make the document as Internet standard?

### ISSUE THREAD

**Issue by lance-lmwang** [veovera/enhanced-rtmp#5]
Thanks for the good job for enhance the RTMP specs,   I'm glad to ask for any plan to publish the document as Internet standard?  Isn't possible to propose the document to IETF like HLS spec and make it more popular and used by more company in the world?

**Comment by veovera** [comment]
The suggestion is a good one and is an internal topic as well...

**Comment by veovera** [comment]
This is not a priority right now, will reopen if in fact this is a must have.
